name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: htfab/tt-gds-action@tt09-ihp-test
        with:
          flow: openlane2
          tools-repo: htfab/tt-support-tools
          tools-ref: tt09-dev

  precheck:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: htfab/tt-gds-action/precheck@tt09-ihp-test
        with:
          tools-repo: htfab/tt-support-tools
          tools-ref: tt09-dev

  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: htfab/tt-gds-action/gl_test@tt09-ihp-test

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: htfab/tt-gds-action/viewer@tt09-ihp-test
